name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    type: [rerequested]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: Build nginx_modsecurity
      run: |
        ( cd nginx_modsecurity
        docker build . )
    - name: Build alfresco
      run: |
        ( cd alfresco/alfresco
        docker build . )
